In [1]:
from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
dataset = load_dataset("lukebarousse/data_jobs")


df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
!pip install -U datasets

Requirement already satisfied: datasets in C:\Users\ahmad\anaconda3\Lib\site-packages (5.0.1)
Requirement already satisfied: filelock in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (4.68.2)
Requirement already satisfied: xxhash in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (1.33.0)
Requirement already satisfied: packaging in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\ahmad\anaconda3\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\ahmad\anaconda3\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in C:\Users\ahmad\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\ahmad\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\ahmad\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\ahmad\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\ahmad\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\ahmad\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\ahmad\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ahmad\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ahmad\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: colorama in C:\Users\ahmad\anaconda3\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ahmad\anaconda3\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ahmad\anaconda3\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ahmad\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /simple/datasets/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /simple/datasets/

In [9]:
df.iloc[0:5]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [21]:
df.loc[0:, 'salary_rate': 'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [23]:
df.loc[0:15, 'salary_rate':].dropna(subset='job_skills')

,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,NaN,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
10,NaN,NaN,NaN,ROCKEN®,"['python', 'databricks', 'azure', 'spark']","{'cloud': ['databricks', 'azure'], 'libraries'..."
11,NaN,NaN,NaN,Philips,"['python', 'qlik']","{'analyst_tools': ['qlik'], 'programming': ['p..."
12,NaN,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
13,NaN,NaN,NaN,Nayya,"['python', 'sql', 'go', 'ruby', 'ruby', 'javas...","{'cloud': ['aws'], 'other': ['terraform'], 'pr..."
14,NaN,NaN,NaN,Oowlish,"['mongodb', 'mongodb']","{'databases': ['mongodb'], 'programming': ['mo..."
15,NaN,NaN,NaN,Orion Group,"['python', 'sql', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."

### Get the first 10 rows of job_skills and job_type_skills

In [24]:
df.loc[:10, 'job_skills':]

,job_skills,job_type_skills
0,NaN,NaN
1,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,"['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,"['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
10,"['python', 'databricks', 'azure', 'spark']","{'cloud': ['databricks', 'azure'], 'libraries'..."

### Get the first 5 columns and rows 10-20

In [26]:
df.loc[10:20, 'job_title_short': 'job_work_from_home']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home
10,Data Engineer,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False
11,Data Engineer,Data Engineer,"Colorado Springs, CO (+3 others)",via The Muse,Full-time,False
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False
13,Senior Data Engineer,Senior Data Engineer,"New York, NY",via LinkedIn,Full-time,False
14,Data Engineer,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",via BeBee,Full-time,False
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False
17,Data Scientist,Data Science Team Lead,"Laurel, MD",via APL Careers - Johns Hopkins University App...,Full-time,False
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False
20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False


Get the first 12 rows of the DataFrame.

In [28]:
df.loc[:11]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
10,Data Engineer,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32,True,False,Switzerland,NaN,NaN,NaN,ROCKEN®,"['python', 'databricks', 'azure', 'spark']","{'cloud': ['databricks', 'azure'], 'libraries'..."
11,Data Engineer,Data Engineer,"Colorado Springs, CO (+3 others)",via The Muse,Full-time,False,"Texas, United States",2023-11-03 13:06:51,False,True,United States,NaN,NaN,NaN,Philips,"['python', 'qlik']","{'analyst_tools': ['qlik'], 'programming': ['p..."

In [11]:
median_salary_year = df['salary_year_avg'].median()

In [13]:
median_salary_hour = df['salary_hour_avg'].median()

### removing the NaN values from the column of salary_year and salary_hour avg

In [18]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [113]:
df_filled['salary_year_avg'].sample(3)

544923    115000.0
496347    115000.0
590186    115000.0
Name: salary_year_avg, dtype: float64

showing the result

In [115]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

To remove duplicates from the dataset

In [121]:
df_unique = df_filled
df_unique =df_unique.drop_duplicates()
print('Length of original datasets ', len(df_filled))
print('Length of dropped duplicates datasets ', len(df_unique))
print('Length of datasets lost ', len(df_filled) - len(df_unique))

Length of original datasets  785741
Length of dropped duplicates datasets  785640
Length of datasets lost  101

To remove duplicates by explicitly citing the column you want to

In [122]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Length of original datasets ', len(df_filled))
print('Length of dropped duplicates datasets ', len(df_unique))
print('Length of datasets lost ', len(df_filled) - len(df_unique))

Length of original datasets  785741
Length of dropped duplicates datasets  508042
Length of datasets lost  277699

In [24]:
minimum_salary = 15000
new_salary =df['salary_year_avg'].fillna(minimum_salary)

In [32]:
new_salary.sample(20)

329472    15000.0
692035    15000.0
175892    15000.0
463097    15000.0
571992    15000.0
563998    15000.0
655055    15000.0
127964    15000.0
696552    15000.0
768615    15000.0
379733    15000.0
108345    15000.0
157439    15000.0
775806    15000.0
53749     15000.0
293790    15000.0
285978    15000.0
288036    15000.0
400354    15000.0
265200    15000.0
Name: salary_year_avg, dtype: float64

In [38]:
new_job_skills = 'python'
update_job_skills = df.job_skills.fillna(new_job_skills)
update_job_skills

0                                                    python
1         ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2         ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3         ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4         ['bash', 'python', 'oracle', 'aws', 'ansible',...
                                ...
785736    ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                       ['sas', 'sas', 'sql', 'excel']
785738                              ['powerpoint', 'excel']
785739    ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                      ['aws', 'flow']
Name: job_skills, Length: 785741, dtype: str

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

To print a percentage from the dataset available

In [47]:
df.sample(frac=0.00001)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
703412,Senior Data Engineer,Senior Data Engineer | Snowflake | 8 Month Con...,"Brisbane City QLD, Australia",via SimplyHired,Contractor,False,Australia,2023-11-02 03:09:43,True,False,Australia,NaN,NaN,NaN,Robert Half,"['python', 'snowflake', 'express', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['snowfl..."
522242,Data Analyst,Data Analyst,"Greenville, SC",via LinkedIn,Full-time,False,Georgia,2023-04-01 11:56:10,False,True,United States,NaN,NaN,NaN,Newrez LLC,"['sql', 'excel', 'powerpoint', 'visio']","{'analyst_tools': ['excel', 'powerpoint', 'vis..."
157684,Data Engineer,"Data Engineer, 270000 Peso mexicano (Remoto en...",Anywhere,via LinkedIn,Full-time,True,Peru,2023-09-22 08:46:06,True,False,Peru,NaN,NaN,NaN,Listopro,['sap'],{'analyst_tools': ['sap']}
232227,Data Analyst,Data Science Analyst (Remote,"Washington, DC",via Thermo Fisher Scientific Jobs,Full-time,False,"New York, United States",2023-09-02 07:00:12,False,True,United States,NaN,NaN,NaN,Thermo Fisher Scientific,"['sql', 'r', 'python', 'sql server', 'aws', 'p...","{'analyst_tools': ['power bi', 'cognos', 'exce..."
526760,Data Analyst,Data Analyst,"Bucharest, Romania",via LinkedIn,Full-time,False,Romania,2023-01-06 12:04:19,False,False,Romania,NaN,NaN,NaN,PAC,"['excel', 'word']","{'analyst_tools': ['excel', 'word']}"
224265,Senior Data Engineer,Senior Data Engineer,"Cary, NC",via MetLife,Full-time,False,Georgia,2023-01-09 07:41:54,False,False,United States,NaN,NaN,NaN,MetLife,"['sql', 'shell', 't-sql', 'powershell', 'sql s...","{'cloud': ['azure'], 'databases': ['sql server..."
455565,Data Engineer,EY - GDS Consulting - D&A -Collibra Data Engin...,"Thiruvananthapuram, Kerala, India",via LinkedIn,Full-time,False,India,2023-06-21 14:13:08,False,False,India,NaN,NaN,NaN,EY,"['sql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'programming': ['s..."
487234,Data Scientist,Data Scientist,"Zürich, Switzerland",via BeBee Schweiz,Full-time,False,Switzerland,2023-01-22 11:54:46,False,False,Switzerland,NaN,NaN,NaN,Raiffeisen Gruppe,"['python', 'sql', 'r', 'azure', 'linux', 'dock...","{'async': ['jira'], 'cloud': ['azure'], 'os': ..."

use of random = 42 or any number

In [56]:
###Sometimes we can have a sample and make it keep repeating the same rows without changing
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

use of .copy()

In [30]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# DataFrame Copy
df_original = df.copy()

In [3]:
df_altered = df_original.copy()
salary_year_avg = df_altered['salary_hour_avg'].max()
df_altered['salary_hour_avg'] = df_altered['salary_hour_avg'].fillna(salary_year_avg)
df_altered['salary_hour_avg'].sample(10)

154175    391.0
535646    391.0
721839    391.0
446054    391.0
571821    391.0
211405    391.0
301441    391.0
89053     391.0
544262    391.0
355549    391.0
Name: salary_hour_avg, dtype: float64

using the .copy() the original dataset was'nt affected

In [4]:
df_original['salary_hour_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_hour_avg, Length: 785741, dtype: float64

while the copied data was affected

In [5]:
###using this kind of method saves you from altering the original data and not making changes that will change the result

df_altered['salary_hour_avg']

0         391.0
1         391.0
2         391.0
3         391.0
4         391.0
          ...
785736    391.0
785737    391.0
785738    391.0
785739    391.0
785740    391.0
Name: salary_hour_avg, Length: 785741, dtype: float64

In [6]:
salary_year_avg = df_altered['salary_year_avg'].min()
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(salary_year_avg)
df_altered

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,15000.0,391.0,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,15000.0,391.0,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,15000.0,391.0,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,15000.0,391.0,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,15000.0,391.0,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,15000.0,391.0,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,15000.0,391.0,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,15000.0,391.0,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,15000.0,391.0,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,15000.0,391.0,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [7]:
df.salary_year_avg.max()

np.float64(960000.0)

In [8]:
df.salary_year_avg.min()

np.float64(15000.0)

PIVOT TABLE

In [ ]:
###A pivot table is a way to summarize and reorganize data into a more readable format. 
# It takes long data and reshapes it into a grid, 
# calculating aggregates (like mean, sum, count) for each combination of categories

df.pivot_table(index='job_title_short', aggfunc='size')

job_title_short
Business Analyst              49063
Cloud Engineer                12331
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Machine Learning Engineer     14080
Senior Data Analyst           29216
Senior Data Engineer          44563
Senior Data Scientist         36957
Software Engineer             44929
dtype: int64

pivoting

In [ ]:
#while pivoting the index reps. the rows, the values reps. the columns
readable_countries = df.pivot_table(index=['job_title_short', 'job_country'], values=['salary_year_avg', 'salary_hour_avg'], aggfunc=['size', 'count', 'sum', 'min', 'max'])
readable_countries.iloc[90:100]

                              size           count                  \
                                 0 salary_hour_avg salary_year_avg
job_title_short  job_country
Business Analyst Myanmar         3               0               0
                 Namibia        49               0               1
                 Nepal          30               0               0
                 Netherlands  1218               0               3
                 New Zealand   299               0               0
                 Nicaragua      19               0               0
                 Nigeria        73               0               4
                 Norway        168               0               0
                 Oman           32               0               0
                 Pakistan       99               1               2

                                         sum                             min  \
                             salary_hour_avg salary_year_avg salary_hour_avg
job_title_short  job_country
Business Analyst Myanmar                 0.0             0.0             NaN
                 Namibia                 0.0        145000.0             NaN
                 Nepal                   0.0             0.0             NaN
                 Netherlands             0.0        257400.0             NaN
                 New Zealand             0.0             0.0             NaN
                 Nicaragua               0.0             0.0             NaN
                 Nigeria                 0.0        372150.0             NaN
                 Norway                  0.0             0.0             NaN
                 Oman                    0.0             0.0             NaN
                 Pakistan               15.0        115200.0            15.0

                                                         max
                             salary_year_avg salary_hour_avg salary_year_avg
job_title_short  job_country
Business Analyst Myanmar                 NaN             NaN             NaN
                 Namibia            145000.0             NaN        145000.0
                 Nepal                   NaN             NaN             NaN
                 Netherlands         63000.0             NaN        105300.0
                 New Zealand             NaN             NaN             NaN
                 Nicaragua               NaN             NaN             NaN
                 Nigeria             63000.0             NaN        110000.0
                 Norway                  NaN             NaN             NaN
                 Oman                    NaN             NaN             NaN
                 Pakistan            50400.0            15.0         64800.0

In [19]:
countries = df.pivot_table(index='job_country', values=['salary_hour_avg', 'salary_year_avg'], aggfunc=['size', 'max'])
countries

             size             max
                0 salary_hour_avg salary_year_avg
job_country
Afghanistan    16             NaN             NaN
Albania       119             NaN        157500.0
Algeria       111            25.0         45000.0
Angola         11             NaN             NaN
Argentina    8736            80.0        222000.0
...           ...             ...             ...
Venezuela      69            80.0             NaN
Vietnam      2414             NaN        200000.0
Yemen          10             NaN             NaN
Zambia        104             NaN         90670.0
Zimbabwe       81             9.0         90670.0

[160 rows x 3 columns]

In [26]:
countries = df.pivot_table(index='job_country', values='salary_year_avg', aggfunc=['min', 'max', 'count'])
countries.sample(20)

                         min             max           count
             salary_year_avg salary_year_avg salary_year_avg
job_country
Kazakhstan           33455.0        157500.0              10
Qatar                    NaN             NaN               0
Nicaragua           111175.0        111175.0               1
Burkina Faso             NaN             NaN               0
Hong Kong            50400.0        147500.0              19
Bolivia                  NaN             NaN               0
Cameroon                 NaN             NaN               0
Slovakia             72900.0        157500.0              16
Bahrain                  NaN             NaN               0
Guadeloupe               NaN             NaN               0
Cyprus               51014.0        191000.0              10
Lebanon              79200.0         96773.0               2
Jamaica             100000.0        100000.0               1
Afghanistan              NaN             NaN               0
Finland              72000.0        185500.0              26
Russia              250000.0        320000.0               4
Vietnam              28000.0        200000.0              55
Luxembourg           53014.0        166000.0              13
Cambodia             89204.0         89204.0               1
Yemen                    NaN             NaN               0

median salary analysis by country

In [29]:
df.pivot_table(columns='job_country', index='job_title_short', values='salary_year_avg', aggfunc='median' )

job_country,Albania,Algeria,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bangladesh,Belarus,...,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vietnam,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,NaN,NaN,71100.00,NaN,70000.0,NaN,NaN,NaN,16500.0,NaN,...,NaN,72900.0,NaN,56700.0,90000.0,NaN,NaN,79200.0,NaN,NaN
Cloud Engineer,NaN,NaN,197500.00,NaN,110000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,89100.0,NaN,NaN,116100.0,NaN,NaN,NaN,NaN,NaN
Data Analyst,49950.00,44100.0,92771.75,100500.0,109500.0,80850.00,NaN,NaN,NaN,400000.0,...,69300.0,72900.0,98500.0,87750.0,90000.0,100500.0,NaN,75550.0,NaN,63000.0
Data Engineer,NaN,45000.0,96773.00,48750.0,106712.5,147500.00,NaN,211000.0,97444.0,NaN,...,NaN,89100.0,97528.0,110000.0,125000.0,NaN,NaN,96773.0,NaN,NaN
Data Scientist,69981.25,NaN,71000.00,NaN,139216.0,71249.75,NaN,NaN,NaN,NaN,...,84200.0,131846.5,166419.5,105300.0,130000.0,NaN,30750.0,70000.0,90670.0,69085.0
Machine Learning Engineer,NaN,NaN,101029.00,87021.0,101029.0,89100.00,NaN,228750.0,69000.0,NaN,...,NaN,89100.0,62850.0,149653.0,150000.0,50000.0,NaN,57600.0,NaN,NaN
Senior Data Analyst,NaN,NaN,NaN,NaN,50640.0,89100.00,NaN,NaN,NaN,NaN,...,NaN,NaN,105837.5,111175.0,110000.0,NaN,NaN,105837.5,NaN,NaN
Senior Data Engineer,NaN,NaN,147500.00,NaN,147500.0,147500.00,NaN,173500.0,NaN,NaN,...,NaN,96773.0,NaN,147500.0,150000.0,NaN,NaN,147500.0,NaN,NaN
Senior Data Scientist,157500.00,NaN,NaN,NaN,157500.0,80850.00,NaN,NaN,NaN,NaN,...,NaN,157500.0,72000.0,157500.0,155000.0,57500.0,NaN,79200.0,NaN,NaN
Software Engineer,NaN,NaN,174500.00,NaN,118350.0,NaN,72000.0,173500.0,NaN,NaN,...,44100.0,54000.0,79200.0,89100.0,130000.0,NaN,NaN,53600.0,NaN,NaN

In [32]:
df.pivot_table(columns= 'job_country', index='job_title_short', values='salary_year_avg', aggfunc=['max'])

                                max                                         \
job_country                 Albania  Algeria Argentina   Armenia Australia
job_title_short
Business Analyst                NaN      NaN   79200.0       NaN  130000.0
Cloud Engineer                  NaN      NaN  197500.0       NaN  110000.0
Data Analyst                56700.0  44100.0  111202.0  100500.0  135000.0
Data Engineer                   NaN  45000.0  147500.0   52500.0  160000.0
Data Scientist              70000.0      NaN  207500.0       NaN  170575.0
Machine Learning Engineer       NaN      NaN  222000.0  128682.0  185500.0
Senior Data Analyst             NaN      NaN       NaN       NaN   71280.0
Senior Data Engineer            NaN      NaN  147500.0       NaN  155500.0
Senior Data Scientist      157500.0      NaN       NaN       NaN  157500.0
Software Engineer               NaN      NaN  174500.0       NaN  257500.0

                                                                               \
job_country                 Austria Azerbaijan   Bahamas Bangladesh   Belarus
job_title_short
Business Analyst                NaN        NaN       NaN    16500.0       NaN
Cloud Engineer                  NaN        NaN       NaN        NaN       NaN
Data Analyst               163782.0        NaN       NaN        NaN  400000.0
Data Engineer              165000.0        NaN  284016.0    97444.0       NaN
Data Scientist              87499.5        NaN       NaN        NaN       NaN
Machine Learning Engineer   89100.0        NaN  246500.0    69000.0       NaN
Senior Data Analyst         89100.0        NaN       NaN        NaN       NaN
Senior Data Engineer       147500.0        NaN  246500.0        NaN       NaN
Senior Data Scientist       80850.0        NaN       NaN        NaN       NaN
Software Engineer               NaN    72000.0  211000.0        NaN       NaN

                           ...                                          \
job_country                ...   Uganda   Ukraine United Arab Emirates
job_title_short            ...
Business Analyst           ...      NaN   72900.0                  NaN
Cloud Engineer             ...      NaN   89100.0                  NaN
Data Analyst               ...  69300.0  111175.0             111175.0
Data Engineer              ...      NaN  147500.0             249000.0
Data Scientist             ...  84200.0  157500.0             166419.5
Machine Learning Engineer  ...      NaN  141000.0              79200.0
Senior Data Analyst        ...      NaN       NaN             111175.0
Senior Data Engineer       ...      NaN   96773.0                  NaN
Senior Data Scientist      ...      NaN  157500.0              79200.0
Software Engineer          ...  44100.0   54000.0              79200.0

                                                                             \
job_country               United Kingdom United States   Uruguay Uzbekistan
job_title_short
Business Analyst                 73500.0      387460.0       NaN        NaN
Cloud Engineer                       NaN      221844.0       NaN        NaN
Data Analyst                    180000.0      375000.0  100500.0        NaN
Data Engineer                   249000.0      525000.0       NaN        NaN
Data Scientist                  205000.0      960000.0       NaN    30750.0
Machine Learning Engineer       200000.0      315000.0   50000.0        NaN
Senior Data Analyst             118140.0      425000.0       NaN        NaN
Senior Data Engineer            171620.0      375000.0       NaN        NaN
Senior Data Scientist           170575.0      475000.0   57500.0        NaN
Software Engineer               160000.0      375000.0       NaN        NaN


job_country                 Vietnam   Zambia Zimbabwe
job_title_short
Business Analyst            79200.0      NaN      NaN
Cloud Engineer                  NaN      NaN      NaN
Data Analyst               200000.0      NaN  63000.0
Data Engineer              165000.0      NaN      NaN
Data Scientist             200000.0  90670.0  90670.0
Machine Learning Engineer  156650.0      NaN      NaN
Senior Data Analyst        111175.0      NaN      NaN
Senior Data Engineer       147500.0      NaN      NaN
Senior Data Scientist       79200.0      NaN      NaN
Software Engineer           79200.0      NaN      NaN

[10 rows x 108 columns]

In [33]:
df.pivot_table(columns= 'job_country', index='job_title_short', values='salary_year_avg', aggfunc='min')

job_country,Albania,Algeria,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bangladesh,Belarus,...,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vietnam,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,NaN,NaN,63000.0,NaN,63000.0,NaN,NaN,NaN,16500.0,NaN,...,NaN,72900.0,NaN,30000.0,35000.0,NaN,NaN,64800.0,NaN,NaN
Cloud Engineer,NaN,NaN,197500.0,NaN,110000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,89100.0,NaN,NaN,42000.0,NaN,NaN,NaN,NaN,NaN
Data Analyst,43200.0,44100.0,45000.0,100500.0,57500.0,53014.0,NaN,NaN,NaN,400000.0,...,69300.0,53014.0,72000.0,30000.0,25000.0,100500.0,NaN,48000.0,NaN,63000.0
Data Engineer,NaN,45000.0,50400.0,45000.0,20000.0,92500.0,NaN,208114.0,97444.0,NaN,...,NaN,50500.0,72960.0,35000.0,23496.0,NaN,NaN,39000.0,NaN,NaN
Data Scientist,69962.5,NaN,50400.0,NaN,81000.0,55000.0,NaN,NaN,NaN,NaN,...,84200.0,43200.0,166419.5,33488.5,30000.0,NaN,30750.0,50400.0,90670.0,47500.0
Machine Learning Engineer,NaN,NaN,70000.0,45360.0,79200.0,89100.0,NaN,211000.0,69000.0,NaN,...,NaN,65000.0,46500.0,85205.0,44408.5,50000.0,NaN,40000.0,NaN,NaN
Senior Data Analyst,NaN,NaN,NaN,NaN,30000.0,89100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,98500.0,79200.0,35360.0,NaN,NaN,79200.0,NaN,NaN
Senior Data Engineer,NaN,NaN,147500.0,NaN,70000.0,89100.0,NaN,173500.0,NaN,NaN,...,NaN,96773.0,NaN,45000.0,45000.0,NaN,NaN,66000.0,NaN,NaN
Senior Data Scientist,157500.0,NaN,NaN,NaN,157500.0,80850.0,NaN,NaN,NaN,NaN,...,NaN,157500.0,64800.0,72500.0,55000.0,57500.0,NaN,79200.0,NaN,NaN
Software Engineer,NaN,NaN,174500.0,NaN,33455.0,NaN,72000.0,173500.0,NaN,NaN,...,44100.0,54000.0,79200.0,89100.0,48982.0,NaN,NaN,28000.0,NaN,NaN

In [36]:
data = df.pivot_table(columns= 'job_title_short', index='job_country', values='salary_year_avg', aggfunc=['min'])
data.head(10)

                             min                                            \
job_title_short Business Analyst Cloud Engineer Data Analyst Data Engineer
job_country
Albania                      NaN            NaN      43200.0           NaN
Algeria                      NaN            NaN      44100.0       45000.0
Argentina                63000.0       197500.0      45000.0       50400.0
Armenia                      NaN            NaN     100500.0       45000.0
Australia                63000.0       110000.0      57500.0       20000.0
Austria                      NaN            NaN      53014.0       92500.0
Azerbaijan                   NaN            NaN          NaN           NaN
Bahamas                      NaN            NaN          NaN      208114.0
Bangladesh               16500.0            NaN          NaN       97444.0
Belarus                      NaN            NaN     400000.0           NaN

                                                                              \
job_title_short Data Scientist Machine Learning Engineer Senior Data Analyst
job_country
Albania                69962.5                       NaN                 NaN
Algeria                    NaN                       NaN                 NaN
Argentina              50400.0                   70000.0                 NaN
Armenia                    NaN                   45360.0                 NaN
Australia              81000.0                   79200.0             30000.0
Austria                55000.0                   89100.0             89100.0
Azerbaijan                 NaN                       NaN                 NaN
Bahamas                    NaN                  211000.0                 NaN
Bangladesh                 NaN                   69000.0                 NaN
Belarus                    NaN                       NaN                 NaN


job_title_short Senior Data Engineer Senior Data Scientist Software Engineer
job_country
Albania                          NaN              157500.0               NaN
Algeria                          NaN                   NaN               NaN
Argentina                   147500.0                   NaN          174500.0
Armenia                          NaN                   NaN               NaN
Australia                    70000.0              157500.0           33455.0
Austria                      89100.0               80850.0               NaN
Azerbaijan                       NaN                   NaN           72000.0
Bahamas                     173500.0                   NaN          173500.0
Bangladesh                       NaN                   NaN               NaN
Belarus                          NaN                   NaN               NaN

In [40]:
df.pivot_table(index='job_title_short', values='salary_year_avg', aggfunc=['count','min', 'median', 'max'])

,count,min,median,max
,salary_year_avg,salary_year_avg,salary_year_avg,salary_year_avg
job_title_short,,,,
Business Analyst,610,16500.0,85000.0,387460.0
Cloud Engineer,65,42000.0,90000.0,280000.0
Data Analyst,5451,25000.0,90000.0,650000.0
Data Engineer,4500,15000.0,125000.0,525000.0
Data Scientist,5922,27000.0,127500.0,960000.0
Machine Learning Engineer,576,30000.0,106415.0,325000.0
Senior Data Analyst,1131,30000.0,111175.0,425000.0
Senior Data Engineer,1591,35000.0,147500.0,425000.0
Senior Data Scientist,1690,45000.0,155500.0,890000.0
Software Engineer,467,28000.0,99150.0,375000.0

In [46]:
data = df.pivot_table(index='job_country', values='salary_year_avg', aggfunc=['count','min', 'median', 'max'])
data.sample(20)

,count,min,median,max
,salary_year_avg,salary_year_avg,salary_year_avg,salary_year_avg
job_country,,,,
Gambia,0,NaN,NaN,NaN
Egypt,20,45000.0,83664.0,166000.0
Brazil,61,15000.0,111175.0,224000.0
New Zealand,28,32400.0,101500.0,249000.0
Maldives,0,NaN,NaN,NaN
Ethiopia,0,NaN,NaN,NaN
Ecuador,0,NaN,NaN,NaN
Slovakia,16,72900.0,89550.0,157500.0
Puerto Rico,37,27000.0,82500.0,375000.0
Bangladesh,3,16500.0,69000.0,97444.0
Estonia,23,50000.0,75000.0,157500.0
Luxembourg,13,53014.0,89100.0,166000.0
Madagascar,0,NaN,NaN,NaN
Oman,0,NaN,NaN,NaN
Israel,103,30000.0,111175.0,192000.0
Paraguay,1,85000.0,85000.0,85000.0
United Arab Emirates,22,46500.0,97528.0,249000.0
Trinidad and Tobago,0,NaN,NaN,NaN
Greece,82,45000.0,96773.0,200000.0
United States,15766,23496.0,119187.5,960000.0